changed python version in test code
Changed python version in test code.

This is so the python version is less explicit. This should hopefully allow me to test the code in different environments easier.

This is so I can change from VS code to  Spyder easier.

This could also allow to code in specific environments easier. An example of this is in VS code where I created the terminal environment, which I labelled 3.10.16 GeoEnv.

I tested my code using pytest code line  : python -m pytest/test/terrain_py-v

this left me with five passes and 2 code failiures. This was using VS code on my windows laptop.

The error message was stated as ================================== short test summary info ===================================
FAILED test/test_terrain.py::TestRegression::test_regression - subprocess.CalledProcessError: Command '['python', 'terrain_analysis.py', '--topography', ...
FAILED test/test_terrain.py::TestRegression::test_regression_verbose - subprocess.CalledProcessError: Command '['python', 'terrain_analysis.py', '--topography', ...
==================== 2 failed, 5 passed, 1 warning in 7405.64s (2:03:25) =====================

It took two hours and three minutes to process. I am not quite sure why, But i aim to get the pytest time reduced and solve the two errors at test_regression and test_regression_verbose which consistantly fail on windows but not on the lineux os.